# Generated by Django 5.1 on 2024-09-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_suggestion_status_suggestion_submitted_at_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='participant',
            field=models.CharField(max_length=200),
        ),
    ]
